name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install And Build
      run: |
        cd src
        npm i
        npm run build
        cd ..
    - name: Move Files
      run: |
        mkdir dist
        mv datas dist/datas
        mv src/assets/ui.css dist/ui.css
        mv src/dist/ui.js dist/ui.js
        mv src/assets/index.html dist/index.html
        mv src/node_modules/jquery/dist/jquery.min.js dist/jquery.min.js
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
